{%set name = "apache-libcloud" %}
{%set version = "1.3.0" %}
{%set hash_type = "sha256" %}
{%set hash_val = "198d86a69f889ded7c023567280f6c479862da5a3d82f70eba7c208bba07b395" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 1000
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - certifi

test:
  imports:
    - libcloud

about:
  home: http://libcloud.apache.org
  license: Apache 2.0
  summary: Python library for interacting with many of the popular cloud service providers using a unified API

extra:
  recipe-maintainers:
    - danielfrg
    - nmadhok
    - tonybaloney
