{% set name = "apache-libcloud" %}
{% set version = "3.3.0" %}
{% set hash_val = "2e3e4d02f9b3197f9119e737bc704fba52f34459d4bc96d8ad8f183d600747ba" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - pip
    - python
    - setuptools
    - pip
  run:
    - python
    - certifi

test:
  imports:
    - libcloud

about:
  home: http://libcloud.apache.org
  license: Apache 2.0
  license_file: LICENSE
  summary: Python library for interacting with many of the popular cloud service providers using a unified API

extra:
  recipe-maintainers:
    - danielfrg
    - nmadhok
    - tonybaloney
