{% set name = "apache-libcloud" %}
{% set version = "3.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-libcloud-{{ version }}.tar.gz
  sha256: 75bf4c0b123bc225e24ca95fca1c35be30b19e6bb85feea781404d43c4276c91

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0
    - requests >=2.26.0

test:
  imports:
    - libcloud
    - libcloud.backup
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://libcloud.apache.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Python library for interacting with many of the popular cloud service providers using a unified API

extra:
  recipe-maintainers:
    - chrisburr
    - nmadhok
    - tonybaloney
