{% set name = "apache-libcloud" %}
{% set version = "2.6.1" %}
{% set hash_type = "sha256" %}
{% set hash_val = "fcc165f2cc2db9a379c6d3a17b3beb9081bb64ba5c0bf7bbb58da864810092f0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
  host:
    - pip
    - python
    - setuptools
    - pip
  run:
    - python
    - certifi

test:
  imports:
    - libcloud

about:
  home: http://libcloud.apache.org
  license: Apache 2.0
  summary: Python library for interacting with many of the popular cloud service providers using a unified API

extra:
  recipe-maintainers:
    - danielfrg
    - nmadhok
    - tonybaloney
