{% set version = "0.18.0" %}

package:
  name: apache-libcloud
  version: {{ version }}

source:
  fn: apache-libcloud-{{ version }}.tar.bz2
  url: http://apache.osuosl.org/libcloud/apache-libcloud-{{ version }}.tar.bz2
  sha1: fbf558d7e52336042dd9a456dec3a73f4b35e38e

  patches:
    # Temporal patch to apply PR https://github.com/apache/libcloud/pull/812
    - certifi.patch

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - certifi

test:
  imports:
    - libcloud

about:
  home: http://libcloud.apache.org
  license: Apache License 2.0
  summary: Python library for interacting with many of the popular cloud service providers using a unified API

extra:
  recipe-maintainers:
    - danielfrg
