{% set name = "apache-libcloud" %}
{% set version = "3.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ace0a87f6d9709c561390f4cb8fcc3b6ddd82af8cddc6f6807fdfeff5aa51a4a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }},<4.0
    - requests >=2.26.0

test:
  imports:
    - libcloud
    - libcloud.backup
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://libcloud.apache.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Python library for interacting with many of the popular cloud service providers using a unified API

extra:
  recipe-maintainers:
    - chrisburr
    - nmadhok
    - tonybaloney
