appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Oxco0TuovTdaLhZaKljfPivPBbDPNIUIglxKzNt0/sebpQSW/OcRgucDKxs2hVgr6E0qZ8rrjUG31FQ+UyoF/pA+Kxree++51ZVpGS64usyP/WBLi/2d3De53P9ccDWnWv/BQyIoLePvktFYyH2c9/h5s3i/3FWEor/FAVclQApEMRKQKXaKPEKm7/MBtWXaoDTWTOjb+kG+EMnWA3BIDDt6bJlYbH49YcUldBy1w4B1S7ItbDqxz5HvhN+mBeOXkptWg/Od6GyF0FU6MgwfLiPmACSnng1nO4ZmZItUHDMxu9JX8ri9u24/glipSFYXZbpjKB88qDUtD+7iflp0X5QIFKN0zJEB0goSIVlrn8UaHTlrl7+So6x1x5GYhcjay+ARqE4kRhX8iU3j2ftI6WQ/rejZFuW69RpuUc+sY19Xd1uPFJK0u+3UHcXuJeZsJYCo+sXmOStRefDig1OfKBWDnSeBnWf+kK0zD5as/xDzp3shIS6zdEkpC4QsnHjHuLE2MpCKalhmFVK+D52Vl69oE718uvkqHhD1beCKAh48zwIy5e4H50JlNfcnYbmTb7sQHsPL7wq0tTzlhMkNJ/4Nvjbt7h7K0uaeW/4N58mBAaA0J63hki748tSSy2T5RS9ss57B+Ann8v6SolH4wpvV8mjorgKTBrz/LbZ5u6A=}
